workspace:
    base: /go
    path: src/github.com/SierraSoftworks/girder

pipeline:

    go:test:
        image: golang:1.6
        commands:
            - go get -u github.com/FiloSottile/gvt
            - gvt restore
            - go test